copy_config:
  delete_destination_db_tables_record_before_copy: false
  tables:
    - name: 'transactions'
      filter: "transaction_date='2018-06-18'"
    - name: 'payments'
      filter: "payment_date='2018-06-18'"
  source_db:
    name: 'shopping_cart'
    host: 'localhost'
    port: 5432
    user_name: 'cart_admin'
    password: 'password'
  destination_db:
    name: 'shopping_cart_test'
    host: 'localhost'
    port: 5432
    user_name: 'cart_admin'
    password: 'password'
